### ISSUE TITLE
Causes the IDE to hang frequently

### ISSUE THREAD

**Issue by SeanSobey** [madskristensen/ErrorHighlighter#12]
### Installed product versions
- Visual Studio: 2015 Enterprise
- This extension: 1.8.42
### Description

Not sure why or how to replicate exactly, but with this extension installed the IDE hangs every minute or so for a few seconds when editing code (.cs, .js, etc).
### Steps to recreate

Not exactly sure unfortunately, but it is across multiple machines. We have a large solution (41 projects) with C# and JS,HTML,CSS,Less code.

Seems to happen most often on save document.
### Current behavior

Causes the editor to freeze for a few seconds.
### Expected behavior

Run smooth and responsive, like when this extension is disabled.

**Comment by IngbertPalm** [comment]
I can confirm the issue! 

When the extension is installed, VS2015 is very unresponsive. After disabling the extension, VS2015 works at normal speed.
Another impression is that the speed of searching (Ctrl+Shift+F) is reduced and that the `Microsoft.Alm.Shared.Remoting.RemoteContainer` process (CodeLens) takes often 100% of CPU power.

**Comment by SamuelEnglard** [comment]
I just did come perf monitoring of VS2015 trying to figure out what's going on and it points here. I can email you the report if you want @madskristensen?

**Comment by madskristensen** [comment]
@samuelenglard please do. Madsk at microsoft com

**Comment by SamuelEnglard** [comment]
@madskristensen will do! From my own research (and attempt to fix) the issue is getting the errors is HEAVY.

**Comment by SamuelEnglard** [comment]
@madskristensen emailed!

**Comment by SamuelEnglard** [comment]
I made some changes in my fork that seem to solve the issue

**Comment by madskristensen** [comment]
Sweet. Due to the holidays I haven't had time to look at this yet. Want to send a pr with your changes?

**Comment by SamuelEnglard** [comment]
I'll have to clean it up some first. I've pushed the changes to GitHub if you want to look before I make the pull request. Probably won't have time to till Tuesday

**Comment by madskristensen** [comment]
Fixed
