### ISSUE TITLE
Since updating to VS2015 eror highlighter doesn't indicate errors anymore?

### ISSUE THREAD

**Issue by MartinL0815** [madskristensen/ErrorHighlighter#13]
### Installed product versions
- Visual Studio: 2015 Premium
- This extension: 1.8.42
### Description

I installed the extensions, I used to live with in VS2013 and I do not see the Error Catcher/Highlighter anymore indicating errors/warnings.
### Steps to recreate
1. start to build the solution
2. compile a file with syntax errors or warnings
3. BuildVision stops the build on the first error
4. no error/warning indicator
### Current behavior

Currently no error/warning indicator is rendered at the top right corner of the text editor in VS2015
### Expected behavior

A rendered error/warnings indicator at the top right corner of the text editor in VS2015

**Comment by madskristensen** [comment]
This should now be fixed in the 2.0 release
