### ISSUE TITLE
Nothing showing in VS.

### ISSUE THREAD

**Issue by smichelotti** [madskristensen/ErrorHighlighter#5]
This extension used to work perfectly for me but it recently stopped working. For *all* files types, it no longer shows the errors in the editor.

I'm running VS Ultimate 2013 with Update 3 (have not yet installed Update 4). Let me know if there is any additional information I can give you to assist.

[UPDATE]: I just updated to Update 4 (for VS Ultimate 2013). I also uninstalled and re-installed the Error Watcher extension. Still nothing is showing. Not sure if there is any other way for me to check what other extension might be getting in the way of this one.

**Comment by Krakean** [comment]
Same issue for me.
VS 2013 + Update 4. 
Reinstalling Error Watcher doesn't help.

**Comment by codingsteff** [comment]
Same issue for me.
VS 2013 + Update 4.

**Comment by madskristensen** [comment]
Fixed in version 1.6

**Comment by codingsteff** [comment]
Thank you Mad, it works!
