### ISSUE TITLE
Add option to show warning and messages only

### ISSUE THREAD

**Issue by lesonkorenac** [madskristensen/ErrorHighlighter#8]
It would be useful if you could add option to show warning and messages in file with no error. 

It would be useful for us since we are currently working on project that has many warning and we want to get rid of them. Our new policy is to get rid of all warnings in refactored/redesigned file before cheking in to master branch. This extension would be a great tool for that.

**Comment by madskristensen** [comment]
That makes sense. I'll add that

**Comment by madskristensen** [comment]
Try out the new build here http://vsixgallery.com/extension/0798393f-f7b0-4283-a36e-c57a73f031c4/

**Comment by lesonkorenac** [comment]
Thank you for quick response. 

I have tried it, but in my opinion it does not behave as expected - all warnings are treated as errors. It can be a little misleading. It would be nice if there would be shown that file contains warning or messages but not treat them as errors.
For example:
Warnings: 3
Messages: 1
